[project]
name = "ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "google-genai>=1.26.0",
    "mcp[cli]>=1.11.0",
    "python-dotenv>=1.1.1",
    "websockets>=15.0.1",
]
